 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/offers", type: :request do
  # Offer. As you add validations to Offer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Offer.create! valid_attributes
      get offers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      offer = Offer.create! valid_attributes
      get offer_url(offer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_offer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      offer = Offer.create! valid_attributes
      get edit_offer_url(offer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Offer" do
        expect {
          post offers_url, params: { offer: valid_attributes }
        }.to change(Offer, :count).by(1)
      end

      it "redirects to the created offer" do
        post offers_url, params: { offer: valid_attributes }
        expect(response).to redirect_to(offer_url(Offer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Offer" do
        expect {
          post offers_url, params: { offer: invalid_attributes }
        }.to change(Offer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post offers_url, params: { offer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested offer" do
        offer = Offer.create! valid_attributes
        patch offer_url(offer), params: { offer: new_attributes }
        offer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the offer" do
        offer = Offer.create! valid_attributes
        patch offer_url(offer), params: { offer: new_attributes }
        offer.reload
        expect(response).to redirect_to(offer_url(offer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        offer = Offer.create! valid_attributes
        patch offer_url(offer), params: { offer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested offer" do
      offer = Offer.create! valid_attributes
      expect {
        delete offer_url(offer)
      }.to change(Offer, :count).by(-1)
    end

    it "redirects to the offers list" do
      offer = Offer.create! valid_attributes
      delete offer_url(offer)
      expect(response).to redirect_to(offers_url)
    end
  end
end
